language: python

python: 3.8

install:
  - pip install --upgrade pip
  - pip install jupyter
  - pip install nbconvert

script:
  - bash scripts/travis/convert-modified-notebooks.sh $TRAVIS_COMMIT_RANGE

deploy:
  provider: script
  script: scripts/travis/push-rst.sh a-la-iqx
  on:
    branch: a-la-iqx
